### ISSUE TITLE
Decide on Django vs other implementation

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/moment#10]
_As Developers, we want to ensure our products are built in the most robust, maintainable, and feature-rich way possible. Evaluate continuing the Moment website Django development vs tearing it down for another implementation_

The current [Moment website](https://moment.materialsdatafacility.org/) is built using Django ([code here](https://github.com/blaiszik/moment-django)). The website is stable, but the code is a little kludgey in places and may be challenging to maintain and build upon. Thus far, it has been a bit of a challenge to do database migration management and is hard to jump into. 

Create a pros and cons document of continuing with Django development vs tearing it down for some other implementation. Some questions to ask yourself are:
- How robust, maintainable, and usable is the Django app (i.e. will it be a pain in the ass?)
- How robust, maintainable, and usable is some other framework?
- How many dev hours (or general effort) will be needed to continue with the Django app vs go with something else?

Please add the document to the [Moment folder in the Garden - CSSI Google Drive](https://drive.google.com/drive/folders/1MFnqGNyiwNenRhBnYfl6VZ4wPPL9RUR7?usp=sharing).

# Assumptions:
1. You can access the [Moment prod website](https://moment.materialsdatafacility.org/) 
2. You can access the ([Django app repo](https://github.com/blaiszik/moment-django))
3. You have some familiarity with Django, SPA frameworks, and web dev in general

# Acceptance Criteria
1. The pros and cons document is comprehensive enough that the team can fairly weigh the options and come to a conclusion
2. We as a team come to a decision and document it somewhere

# Tasks
- [ ] Get the lay of the land of the Django app code and current outstanding issues 
- [ ] Investigate other frameworks and design approaches (e.g. React, Vue.js, something else entirely)
- [ ] Create a comprehensive pros/cons list of keeping the Django app vs switching
   - [ ] Estimate the amount of effort for each 
- [ ] Present findings to the team
   - [ ] Reach a decision and record it somewhere

**Comment by vladx2** [comment]
With the current approach, the frontend is going to be something much more static, so we'll need something that's the least amount of effort to maintain and update – i.e. not the current Django app.

We'll know what exactly closer to the start of the first cohort, but likely the most popular framework that the rest of the Accelerate team who are into frontends knows too, to minimise overheads.
