### ISSUE TITLE
Update pitch slides for Research Teams

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/moment#13]
We are iterating on our current pitch slide deck for Research Teams 

Current public-facing slidedeck: [Moment for Research Teams](https://docs.google.com/presentation/d/1-znSB19EoKKpeQu7H9Hl0DgnskW2bozSY3ST-Ve-GcY/edit?usp=sharing)

WIP updated slide deck:  [(Internal) Moment for Research Teams](https://docs.google.com/presentation/d/1hx_rHtCk0fW7_W7nXJssvjmOXzpPDwdVR5OjKFjGq5k/edit?usp=sharing)

We want to make sure we communicate the following ideasL
- Communicate goals at the beginning of pitches
- Clarify that we need project ideas from *them*

# Tasks
- [x] Add content for beginning slide re: goals of the meeting 
- [x] Add content for end slide re: action items, what we need
- [x] Update the slides with one of the SlidesGo templates (see below)

## Potential slides templates
https://slidesgo.com/theme/simple-meeting#search-Simple+professional&position-1&results-1273&rs=search 
https://slidesgo.com/theme/minimalist-geometric-shapes-style-pitch-deck#search-Minimalist&position-17&results-2536&rs=search 
https://slidesgo.com/theme/business-plan-minimalist-aesthetics#search-Minimalist&position-41&results-2536&rs=search&rs=search

**Comment by vladx2** [comment]
Drafting a new version [here](https://docs.google.com/presentation/d/1hx_rHtCk0fW7_W7nXJssvjmOXzpPDwdVR5OjKFjGq5k/edit?usp=sharing).

When it's finished, I will move the slides over to the [canonical slides](https://docs.google.com/presentation/d/1-znSB19EoKKpeQu7H9Hl0DgnskW2bozSY3ST-Ve-GcY/edit?usp=sharing) that are already shared with teams.

**Comment by ascourtas** [comment]
Updated to a shiny new theme! [slide deck can be found here](https://docs.google.com/presentation/d/1_52R_8G96uLqaiKAvSLEL0-gVwMsdxzCno7C8SUUV9Y/edit#slide=id.p) -- just waiting for Vlad's review

<img width="952" alt="Screenshot 2024-03-06 at 3 24 15 PM" src="https://github.com/Garden-AI/moment/assets/18538526/24753ae5-9aba-465d-82f3-32c49f4f25f8">
