### ISSUE TITLE
Moment User Research v0 -- User feedback

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/moment#9]
_As Product Owners and Developers, we want to ensure Moment is going in the right direction and meeting user needs._

Our [original Moment platform](https://moment.materialsdatafacility.org/) (the Django app, aka vEthan) had some initial usage and engagement by real users. These users' experiences are not documented anywhere, and we want to learn what was effective about the platform and what was not in its vEthan iteration. Logan and Noah worked with Moment and users using Moment.

Talk with Logan and Noah re: how using Moment has gone, pain points identified, etc. and create a document chronicling what was good, what was bad, and what needed improvement. Some questions to ask Logan and Noah could include:
- What users did you engage with? 
- For what purposes did users (or yourselves) use Moment?
- What worked well with Moment?
- What did not work well?
- Would you continue using Moment in its current form? If not, what would it need to convince you?
- What do you think other users would need to convince them Moment was worth it?
- Do you have any other proposed changes?

Please document your questions and answers in the [Moment v0 User Research Google doc](https://docs.google.com/document/d/1XTSAjnhYEtyL5JJgEHHExk2JiPqEmoH9fW3CElRNx6Q/edit?usp=sharing)

# Assumptions:
1. You are able to meet with Logan and Noah
2. Logan and Noah are the primary users (this could be mistaken -- it's possible there are others we should talk to)

# Acceptance Criteria
1. Given the interviews with Logan and Noah, we have a clear understanding of what was good, what was bad, and what needs to change about Moment. 
2. Given the presentation of the findings to the team, the team can decide on next steps with regards to Moment development 

# Tasks 
- [x] Set up meetings with Noah and Logan to interview them about Moment, ask for more info, etc
- [x] [Document Q&A](https://docs.google.com/document/d/1XTSAjnhYEtyL5JJgEHHExk2JiPqEmoH9fW3CElRNx6Q/edit?usp=sharing) clearly and thoroughly
- [x] Determine if there are other users we should interview (used US-RSE guidebook instead)
- [x] (optional) Potentially set up meetings with any other users, if applicable (not needed)
- [x] Discuss with Ari
- [ ] Create presentation slides
- [ ] Present findings to the rest of team in Accelerate or Gathertown meetings, or in an asynch format

**Comment by ascourtas** [comment]
NOTE: scoot this to the community board for better organization

**Comment by ascourtas** [comment]
Presentation scheduled for Oct 24th during Gathertown time

**Comment by ascourtas** [comment]
completed! Discussed with Noah, (someone else?), and consulted the US-RSE Guidebook.

User interviews (internal): https://docs.google.com/document/d/1XTSAjnhYEtyL5JJgEHHExk2JiPqEmoH9fW3CElRNx6Q/edit?usp=sharing

US-RSE Guidebook: https://zenodo.org/records/8274378

Final Moment project proposal as a result of this research can be found here (internal): https://docs.google.com/presentation/d/1mON2vLbIA5vo3IjO30bgZ_XXTl79dEmHqMdTEG-dTsE/edit?usp=sharing
